<a href="https://colab.research.google.com/github/HwangHanJae/ai_for_linalg/blob/main/scalar_vector_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

scalar : 숫자 - ${1}, {2}, {2.3}$

vector : 리스트 형태의 숫자 - $x = [1\;0\;2]\;or\;x = \begin{bmatrix}1\\0\\2\end{bmatrix}$

matrix : 2차원 리스트형태의 숫자 - $A = \begin{bmatrix}1&4\\2&5\\3&6\end{bmatrix}$ 

In [3]:
#라이브러리 로드
import numpy as np

scalar = 1

vector = np.array([1, 0, 2])

matrix = np.array([[1,4],[2,5],[3,6]])

print("scalar : \n", scalar)
print("vector : \n", vector)
print("matrix : \n", matrix)


scalar : 
 1
vector : 
 [1 0 2]
matrix : 
 [[1 4]
 [2 5]
 [3 6]]


넘파이 라이브러리를 사용하면 vector와 matrix로 쉽게 형태를 바꿀 수 있음

vector를 표현할때 기본적으로 열벡터(column vector)  x = $\begin{bmatrix}1\\0\\2\end{bmatrix}$의 모습을 사용한다.

행백터(row vector)는 보통 열벡터를 transpose하여 표현한다. - $x^T=\begin{bmatrix}1\\0\\2\end{bmatrix}^{T}$


정방행렬(Square matrix) : row와 column의 길이가 서로 같을때  
ex) : $Square\;matrix = \begin{bmatrix}1&3\\2&4\end{bmatrix}$

직사각행렬(Rectangular matrix) : row와 column의 길이가 서로 다를때  
ex) : $Rectangular\;matrix = A = \begin{bmatrix}1&4\\2&5\\3&6\end{bmatrix}$

전치행렬(Transpose Matrix) : 위의 직사각행렬을 전치해보았을 때 :  
ex) : $Transpose\;Matrix = A^T = \begin{bmatrix}1&2&3\\4&5&6\end{bmatrix}$

In [5]:
test_array = [[1,4],[2,5],[3,6]]
A = np.array(test_array)
print('A : \n', A)

A_t = A.transpose()

print("A_t : \n", A_t)

A : 
 [[1 4]
 [2 5]
 [3 6]]
A_t : 
 [[1 2 3]
 [4 5 6]]


transpose() 함수를 사용하면 전치행렬을 만들 수 있음

vector를 연산할때 분배법칙이나 결합법칙이 가능하다.

하지만 matrix를 사용하여 연산을 할때는 조심해야한다.  
A(2x3)와B(3x5)와 같은 형태의 matrix가 존재할 때 AxB는 가능하지만
BxA는 가능하지 않다.  

In [11]:
a = np.arange(6).reshape(2,3)
b = np.arange(15).reshape(3,5)

print('a : \n',a)
print('b : \n',b)

print("AB : \n", np.matmul(a,b))
print("BA : \n", np.matmul(b, a))

a : 
 [[0 1 2]
 [3 4 5]]
b : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
AB : 
 [[ 25  28  31  34  37]
 [ 70  82  94 106 118]]


ValueError: ignored

AB는 정상적으로 실행이 되지만, BA는 정상적으로 실행되지 않는 것을 확인할 수 있다.

A(2x3) B(3x5)는 A의 열과 B의 행의 숫자가 같으니 이것을 보고 가능과 불가능을 확인할 수 있다. AB의 결과는 2x5의 결과가 나오게 된다.

A(2x2), B(2x2) 있을때 AB != BA의 결과가 나오게 된다.

In [14]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8).reshape(2,2)

print('a : \n',a)
print('b : \n',b)

print("AB : \n", np.matmul(a,b))
print("BA : \n", np.matmul(b,a))

a : 
 [[0 1]
 [2 3]]
b : 
 [[4 5]
 [6 7]]
AB : 
 [[ 6  7]
 [26 31]]
BA : 
 [[10 19]
 [14 27]]
